services:
  app:
    container_name: mydrive
    build: .
    image: el-choco/mydrive:local
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - /home/mydrive/data:/data/
      - /home/mydrive/temp:/temp/
    ports:
      - "4100:3000"
    env_file:
      - .env
    networks:
      - mydrive-net

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    volumes:
      - db-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "-u", "username", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - mydrive-net

volumes:
  mydrive-data:
  mydrive-temp:
  db-data:

networks:
  mydrive-net:
    driver: bridge